version: "3.9"

services:
  backend:
    build: ./server
    container_name: app-backend
    restart: always
    env_file: ./server/.env.production
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    build: ./client
    container_name: app-frontend
    restart: always
    env_file: ./client/.env.production
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
networks:
  app-network:
    driver: bridge